In [1]:
import numpy as np

Um array é como se fosse uma lista, mas ele possui propriedades proprias dentro do numpy, seu tipo de dado é ndarray( ou array de n dimensões)

1D array(Array de uma dimensão) -> vetor/vector
2D array(Array de duas dimensões) -> matriz/matrix
3D array(Array de tres dimensõess) -> Tensor
nD array(Array com mais de tres dimensões) -> tensor

In [19]:
array = np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[9,8,7,6,5],[2,3,4,6,7]]]) # Isto é um tensor, ele é construido como uma lista de arrays, todos do mesmo tamanho, utilizando a função p.array()
print(array)

[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[9 8 7 6 5]
  [2 3 4 6 7]]]


In [17]:
array_zero = np.zeros(shape = (5,3,6)) # np.zero cria um array apenas com zeros. o parametro shape define o tamanho das dimensões, 
# ou seja, as dimensões são respectivamente de tamanhos 5, 3, e 6. 
print(array_zero)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
